services:
  bocchi:
    build: .
    container_name: bocchi
    restart: unless-stopped
  environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
